---
version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - alchemy

  broker:
    image: confluentinc/cp-kafka:7.3.0
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
      - "9101:9101"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CLEANUP_POLICY: "compact"
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    networks:
      - alchemy

  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker:29092
      # SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - alchemy

  kafka-rest:
    image: confluentinc/cp-kafka-rest:7.3.0
    container_name: kafka-rest
    ports:
      - "8082:8082"
    depends_on:
      - broker
      - zookeeper
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: "broker:29092"
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
    networks:
      - alchemy

  connectors:
    # image: confluentinc/cp-kafka-connect:7.3.0
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: connectors
    hostname: connectors
    ports:
      - "8083:8083"
    depends_on:
      - broker
      - zookeeper
    environment:
      CONNECT_GROUP_ID : 1
      CONNECT_BOOTSTRAP_SERVERS: "broker:29092"
      CONNECT_REST_ADVERTISED_HOST_NAME: "connectors"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_STORAGE_TOPIC: connect_configs_cleanup_policy_compact
      CONNECT_STATUS_STORAGE_TOPIC: connect_statuses_cleanup_policy_compact
      CONNECT_OFFSET_STORAGE_TOPIC: connect_offsets
      CONNECT_CLEANUP_POLICY: "compact"
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      # CONNECT_CONFIG_STORAGE_SECRETS_PROVIDER: "confluent_secrets_provider"
      # CONNECT_CONFIG_PROVIDERS: "secret"
      # CONNECT_CONFIG_PROVIDERS_SECRET_CLASS: "io.confluent.connect.secretregistry.rbac.config.provider.InternalSecretConfigProvider"
    networks:
      - alchemy


  ksql:
    image: confluentinc/cp-ksql-server:5.4.10
    container_name: ksql
    ports:
      - "8088:8088"
    depends_on:
      - broker
      - zookeeper
    environment:
      KSQL_BOOTSTRAP_SERVERS: "broker:29092"
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_KSQL_SERVICE_ID: "ksql-service"
    networks:
      - alchemy

  debezium-ui:
    image: debezium/debezium-ui:latest
    restart: always
    container_name: debezium-ui
    hostname: debezium-ui
    depends_on:
      - connectors
    ports:
      - "8080:8080"
    environment:
      KAFKA_CONNECT_URIS: http://connectors:8083
    networks:
      - alchemy


networks:
  alchemy:

